# Generated by Django 5.2.1 on 2026-10-02 06:37

import core.panels
import datetime
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("blog", "0007_preserve_subtitle_text"),
        ("catalog", "0009_organizationtype_ratings_image_and_more"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaqCategoryGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="Title")),
                (
                    "title_ru",
                    models.CharField(max_length=120, null=True, verbose_name="Title"),
                ),
                (
                    "title_ka",
                    models.CharField(max_length=120, null=True, verbose_name="Title"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=120, null=True, verbose_name="Title"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sort order"),
                ),
            ],
            options={
                "verbose_name": "FAQ category group",
                "verbose_name_plural": "FAQ category groups",
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="FaqIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", models.TextField(blank=True, verbose_name="Introduction")),
                (
                    "intro_ru",
                    models.TextField(
                        blank=True, null=True, verbose_name="Introduction"
                    ),
                ),
                (
                    "intro_ka",
                    models.TextField(
                        blank=True, null=True, verbose_name="Introduction"
                    ),
                ),
                (
                    "intro_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Introduction"
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ index page",
                "verbose_name_plural": "FAQ index pages",
                "abstract": False,
            },
            bases=(core.panels.Panels, "wagtailcore.page"),
        ),
        migrations.CreateModel(
            name="FaqCategoryPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", models.TextField(blank=True, verbose_name="Introduction")),
                (
                    "intro_ru",
                    models.TextField(
                        blank=True, null=True, verbose_name="Introduction"
                    ),
                ),
                (
                    "intro_ka",
                    models.TextField(
                        blank=True, null=True, verbose_name="Introduction"
                    ),
                ),
                (
                    "intro_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Introduction"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sort order"),
                ),
                (
                    "blog_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="blog.blogcategorypage",
                        verbose_name="Blog category",
                    ),
                ),
                (
                    "catalog_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalog.organizationtype",
                        verbose_name="Catalog category",
                    ),
                ),
                (
                    "cover",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Cover",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="categories",
                        to="faq.faqcategorygroup",
                        verbose_name="FAQ category group",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ category page",
                "verbose_name_plural": "FAQ category pages",
                "abstract": False,
            },
            bases=(core.panels.Panels, "wagtailcore.page"),
        ),
        migrations.CreateModel(
            name="FaqQuestionPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Subtitle"
                    ),
                ),
                (
                    "subtitle_ru",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Subtitle"
                    ),
                ),
                (
                    "subtitle_ka",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Subtitle"
                    ),
                ),
                (
                    "subtitle_en",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Subtitle"
                    ),
                ),
                ("short_answer", models.TextField(verbose_name="Short answer")),
                (
                    "short_answer_ru",
                    models.TextField(null=True, verbose_name="Short answer"),
                ),
                (
                    "short_answer_ka",
                    models.TextField(null=True, verbose_name="Short answer"),
                ),
                (
                    "short_answer_en",
                    models.TextField(null=True, verbose_name="Short answer"),
                ),
                (
                    "why_points",
                    wagtail.fields.StreamField(
                        [("point", 0)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"label": "Point"})
                        },
                        verbose_name="Why",
                    ),
                ),
                (
                    "why_points_ru",
                    wagtail.fields.StreamField(
                        [("point", 0)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"label": "Point"})
                        },
                        null=True,
                        verbose_name="Why",
                    ),
                ),
                (
                    "why_points_ka",
                    wagtail.fields.StreamField(
                        [("point", 0)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"label": "Point"})
                        },
                        null=True,
                        verbose_name="Why",
                    ),
                ),
                (
                    "why_points_en",
                    wagtail.fields.StreamField(
                        [("point", 0)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"label": "Point"})
                        },
                        null=True,
                        verbose_name="Why",
                    ),
                ),
                (
                    "details",
                    wagtail.fields.RichTextField(blank=True, verbose_name="Details"),
                ),
                (
                    "details_ru",
                    wagtail.fields.RichTextField(
                        blank=True, null=True, verbose_name="Details"
                    ),
                ),
                (
                    "details_ka",
                    wagtail.fields.RichTextField(
                        blank=True, null=True, verbose_name="Details"
                    ),
                ),
                (
                    "details_en",
                    wagtail.fields.RichTextField(
                        blank=True, null=True, verbose_name="Details"
                    ),
                ),
                ("tip", models.TextField(blank=True, verbose_name="Tip")),
                ("tip_ru", models.TextField(blank=True, null=True, verbose_name="Tip")),
                ("tip_ka", models.TextField(blank=True, null=True, verbose_name="Tip")),
                ("tip_en", models.TextField(blank=True, null=True, verbose_name="Tip")),
                (
                    "may_differ",
                    models.TextField(blank=True, verbose_name="What may differ"),
                ),
                (
                    "may_differ_ru",
                    models.TextField(
                        blank=True, null=True, verbose_name="What may differ"
                    ),
                ),
                (
                    "may_differ_ka",
                    models.TextField(
                        blank=True, null=True, verbose_name="What may differ"
                    ),
                ),
                (
                    "may_differ_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="What may differ"
                    ),
                ),
                (
                    "myth",
                    models.TextField(blank=True, verbose_name="Common misconception"),
                ),
                (
                    "myth_ru",
                    models.TextField(
                        blank=True, null=True, verbose_name="Common misconception"
                    ),
                ),
                (
                    "myth_ka",
                    models.TextField(
                        blank=True, null=True, verbose_name="Common misconception"
                    ),
                ),
                (
                    "myth_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Common misconception"
                    ),
                ),
                (
                    "myth_truth",
                    models.TextField(blank=True, verbose_name="What actually happens"),
                ),
                (
                    "myth_truth_ru",
                    models.TextField(
                        blank=True, null=True, verbose_name="What actually happens"
                    ),
                ),
                (
                    "myth_truth_ka",
                    models.TextField(
                        blank=True, null=True, verbose_name="What actually happens"
                    ),
                ),
                (
                    "myth_truth_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="What actually happens"
                    ),
                ),
                (
                    "people_also_ask",
                    wagtail.fields.StreamField(
                        [("question", 0)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"label": "Question"})
                        },
                        verbose_name="People also ask",
                    ),
                ),
                (
                    "people_also_ask_ru",
                    wagtail.fields.StreamField(
                        [("question", 0)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"label": "Question"})
                        },
                        null=True,
                        verbose_name="People also ask",
                    ),
                ),
                (
                    "people_also_ask_ka",
                    wagtail.fields.StreamField(
                        [("question", 0)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"label": "Question"})
                        },
                        null=True,
                        verbose_name="People also ask",
                    ),
                ),
                (
                    "people_also_ask_en",
                    wagtail.fields.StreamField(
                        [("question", 0)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"label": "Question"})
                        },
                        null=True,
                        verbose_name="People also ask",
                    ),
                ),
                (
                    "sources",
                    wagtail.fields.StreamField(
                        [("source", 5)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Source name (ru)", "required": False},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Source name (ka)", "required": False},
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Source name (en)", "required": False},
                            ),
                            3: ("wagtail.blocks.URLBlock", (), {"label": "URL"}),
                            4: (
                                "wagtail.blocks.DateBlock",
                                (),
                                {"label": "Checked at"},
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("name_ru", 0),
                                        ("name_ka", 1),
                                        ("name_en", 2),
                                        ("url", 3),
                                        ("checked_at", 4),
                                    ]
                                ],
                                {},
                            ),
                        },
                        verbose_name="Sources",
                    ),
                ),
                (
                    "important_note",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Important note"
                    ),
                ),
                (
                    "important_note_ru",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Important note",
                    ),
                ),
                (
                    "important_note_ka",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Important note",
                    ),
                ),
                (
                    "important_note_en",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Important note",
                    ),
                ),
                (
                    "answered_at",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Answered at"
                    ),
                ),
                (
                    "checked_at",
                    models.DateField(
                        db_index=True,
                        default=datetime.date.today,
                        verbose_name="Checked at",
                    ),
                ),
                (
                    "cta_url",
                    models.URLField(
                        blank=True, max_length=2000, verbose_name="Read more URL"
                    ),
                ),
                (
                    "cta_label",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Read more label"
                    ),
                ),
                (
                    "cta_label_ru",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Read more label",
                    ),
                ),
                (
                    "cta_label_ka",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Read more label",
                    ),
                ),
                (
                    "cta_label_en",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Read more label",
                    ),
                ),
                (
                    "related_questions",
                    wagtail.fields.StreamField(
                        [("question", 0)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"page_type": ["faq.FaqQuestionPage"]},
                            )
                        },
                        verbose_name="Related questions",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True, max_length=2000, verbose_name="YouTube URL"
                    ),
                ),
                (
                    "is_popular",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Popular question"
                    ),
                ),
                (
                    "cover",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Cover",
                    ),
                ),
                (
                    "cta_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                        verbose_name="Read more page",
                    ),
                ),
                (
                    "social_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Social image",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ question page",
                "verbose_name_plural": "FAQ question pages",
                "abstract": False,
            },
            bases=(core.panels.Panels, "wagtailcore.page"),
        ),
        migrations.CreateModel(
            name="FaqTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_items",
                        to="faq.faqquestionpage",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to="taggit.tag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="faqquestionpage",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="faq.FaqTag",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
