# Generated by Django 5.2.1 on 2026-10-02 08:03

import wagtail.fields
from html import escape, unescape
from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.utils.html import strip_tags


def convert_editor_text(
    apps: Apps, schema_editor: BaseDatabaseSchemaEditor, *, reverse: bool = False
) -> None:
    """Preserve plain text in rich-text fields, including existing draft revisions."""
    alias = schema_editor.connection.alias
    revision = apps.get_model("wagtailcore", "Revision")
    content_type = apps.get_model("contenttypes", "ContentType")
    for model_name, bases in (
        ("FaqIndexPage", ("intro",)),
        ("FaqCategoryPage", ("intro",)),
        ("FaqQuestionPage", ("tip", "may_differ", "myth", "myth_truth")),
    ):
        model = apps.get_model("faq", model_name)
        fields = [
            field.name
            for field in model._meta.fields
            if any(
                field.name == base or field.name.startswith(base + "_")
                for base in bases
            )
        ]

        def convert(value: str | None) -> str | None:
            if not value:
                return value
            if reverse:
                return unescape(
                    strip_tags(value.replace("</p><p>", "\n\n").replace("<br/>", "\n"))
                )
            return "".join(
                "<p>" + escape(paragraph).replace("\n", "<br/>") + "</p>"
                for paragraph in value.replace("\r\n", "\n").split("\n\n")
            )

        for page in model.objects.using(alias).only("pk", *fields).iterator():
            model.objects.using(alias).filter(pk=page.pk).update(
                **{field: convert(getattr(page, field)) for field in fields}
            )
        types = (
            content_type.objects.using(alias)
            .filter(app_label="faq", model=model_name.lower())
            .values_list("pk", flat=True)
        )
        for item in (
            revision.objects.using(alias).filter(content_type_id__in=types).iterator()
        ):
            data = dict(item.content)
            for field in fields:
                if field in data and isinstance(data[field], str):
                    data[field] = convert(data[field])
            revision.objects.using(alias).filter(pk=item.pk).update(content=data)


def forwards(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    convert_editor_text(apps, schema_editor)


def backwards(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    convert_editor_text(apps, schema_editor, reverse=True)


class Migration(migrations.Migration):
    dependencies = [
        ("faq", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name="faqcategorypage",
            name="intro",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="Introduction"),
        ),
        migrations.AlterField(
            model_name="faqcategorypage",
            name="intro_en",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="Introduction"
            ),
        ),
        migrations.AlterField(
            model_name="faqcategorypage",
            name="intro_ka",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="Introduction"
            ),
        ),
        migrations.AlterField(
            model_name="faqcategorypage",
            name="intro_ru",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="Introduction"
            ),
        ),
        migrations.AlterField(
            model_name="faqindexpage",
            name="intro",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="Introduction"),
        ),
        migrations.AlterField(
            model_name="faqindexpage",
            name="intro_en",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="Introduction"
            ),
        ),
        migrations.AlterField(
            model_name="faqindexpage",
            name="intro_ka",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="Introduction"
            ),
        ),
        migrations.AlterField(
            model_name="faqindexpage",
            name="intro_ru",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="Introduction"
            ),
        ),
        migrations.AlterField(
            model_name="faqquestionpage",
            name="may_differ",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="What may differ"
            ),
        ),
        migrations.AlterField(
            model_name="faqquestionpage",
            name="may_differ_en",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="What may differ"
            ),
        ),
        migrations.AlterField(
            model_name="faqquestionpage",
            name="may_differ_ka",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="What may differ"
            ),
        ),
        migrations.AlterField(
            model_name="faqquestionpage",
            name="may_differ_ru",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="What may differ"
            ),
        ),
        migrations.AlterField(
            model_name="faqquestionpage",
            name="myth",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="Common misconception"
            ),
        ),
        migrations.AlterField(
            model_name="faqquestionpage",
            name="myth_en",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="Common misconception"
            ),
        ),
        migrations.AlterField(
            model_name="faqquestionpage",
            name="myth_ka",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="Common misconception"
            ),
        ),
        migrations.AlterField(
            model_name="faqquestionpage",
            name="myth_ru",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="Common misconception"
            ),
        ),
        migrations.AlterField(
            model_name="faqquestionpage",
            name="myth_truth",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="What actually happens"
            ),
        ),
        migrations.AlterField(
            model_name="faqquestionpage",
            name="myth_truth_en",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="What actually happens"
            ),
        ),
        migrations.AlterField(
            model_name="faqquestionpage",
            name="myth_truth_ka",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="What actually happens"
            ),
        ),
        migrations.AlterField(
            model_name="faqquestionpage",
            name="myth_truth_ru",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="What actually happens"
            ),
        ),
        migrations.AlterField(
            model_name="faqquestionpage",
            name="tip",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="Tip"),
        ),
        migrations.AlterField(
            model_name="faqquestionpage",
            name="tip_en",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="Tip"
            ),
        ),
        migrations.AlterField(
            model_name="faqquestionpage",
            name="tip_ka",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="Tip"
            ),
        ),
        migrations.AlterField(
            model_name="faqquestionpage",
            name="tip_ru",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="Tip"
            ),
        ),
    ]
