# Generated by Django 5.2.1 on 2026-05-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_sitesettings_ad_button_caption_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="slogan",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="slogan_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="slogan_ka",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="slogan_ru",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
