# Generated by Django 5.2.1 on 2026-08-19 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="authorsindexpage",
            options={
                "verbose_name": "Authors index page",
                "verbose_name_plural": "Authors index pages",
            },
        ),
    ]
