# Generated by Django 5.2.1 on 2026-05-11 11:07

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_gallerycategorypage_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryindexpage",
            name="description",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="galleryindexpage",
            name="description_en",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="galleryindexpage",
            name="description_ka",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="galleryindexpage",
            name="description_ru",
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
