# Generated by Django 5.2.1 on 2026-08-14 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0003_galleryindexpage_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gallerycategorypage",
            options={
                "verbose_name": "Gallery category page",
                "verbose_name_plural": "Gallery category pages",
            },
        ),
        migrations.AlterModelOptions(
            name="galleryindexpage",
            options={
                "verbose_name": "Gallery index page",
                "verbose_name_plural": "Gallery index pages",
            },
        ),
        migrations.AlterModelOptions(
            name="gallerypostpage",
            options={
                "verbose_name": "Gallery post page",
                "verbose_name_plural": "Gallery post pages",
            },
        ),
    ]
