# Generated by Django 5.2.1 on 2026-08-31 09:32

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("comments", "0002_comment_pin"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="comment",
            index=models.Index(
                fields=["content_type", "object_id", "user", "parent", "created_at"],
                name="comments_import_lookup_idx",
            ),
        ),
        AddIndexConcurrently(
            model_name="comment",
            index=models.Index(
                fields=["tree_id", "lft"], name="comments_comment_tree_id_l4b1c"
            ),
        ),
    ]
