# Generated by Django 5.2.1 on 2026-08-14 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ratingcategorypage",
            options={
                "verbose_name": "Overviews category page",
                "verbose_name_plural": "Overviews category pages",
            },
        ),
        migrations.AlterModelOptions(
            name="ratingpage",
            options={
                "verbose_name": "Overviews post page",
                "verbose_name_plural": "Overviews post pages",
            },
        ),
        migrations.AlterModelOptions(
            name="ratingsindexpage",
            options={
                "verbose_name": "Overviews index page",
                "verbose_name_plural": "Overviews index pages",
            },
        ),
    ]
