# Generated by Django 5.2.1 on 2026-08-14 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_bloggallery_alter_blogpostpage_content_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogcategorypage",
            options={
                "verbose_name": "Blog category page",
                "verbose_name_plural": "Blog category pages",
            },
        ),
        migrations.AlterModelOptions(
            name="blogindexpage",
            options={
                "verbose_name": "Blog index page",
                "verbose_name_plural": "Blog index pages",
            },
        ),
        migrations.AlterModelOptions(
            name="blogpostpage",
            options={
                "verbose_name": "Blog post page",
                "verbose_name_plural": "Blog post pages",
            },
        ),
    ]
