# Generated by Django 5.2.1 on 2026-08-31 09:32

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("reviews", "0002_alter_review_rating"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="review",
            index=models.Index(
                fields=["content_type", "object_id", "user"],
                name="reviews_import_lookup_idx",
            ),
        ),
        AddIndexConcurrently(
            model_name="review",
            index=models.Index(
                fields=["content_type", "object_id", "status", "rating"],
                name="reviews_rating_lookup_idx",
            ),
        ),
    ]
