# Generated by Django 5.2.1 on 2026-08-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_city_content_alter_city_content_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="avg_rating",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=3, verbose_name="Average rating"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="rating_score",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=3, verbose_name="Rating score"
            ),
        ),
    ]
