# Generated by Django 5.2.1 on 2026-09-15 14:38

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_organization_avg_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="banners",
            field=wagtail.fields.StreamField(
                [("banner", 7)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "max_length": 255, "required": False},
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Description", "required": False},
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image"},
                    ),
                    3: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Page", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "URL", "max_length": 2000, "required": False},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Button text", "max_length": 50, "required": False},
                    ),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("purple-red", "Purple-Red"),
                                ("blue-green", "Blue-Green"),
                                ("light-blue", "Light Blue"),
                            ],
                            "label": "Color",
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("description", 1),
                                ("image", 2),
                                ("page", 3),
                                ("url", 4),
                                ("button_text", 5),
                                ("style", 6),
                            ]
                        ],
                        {},
                    ),
                },
                verbose_name="Banners",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="banners_en",
            field=wagtail.fields.StreamField(
                [("banner", 7)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "max_length": 255, "required": False},
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Description", "required": False},
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image"},
                    ),
                    3: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Page", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "URL", "max_length": 2000, "required": False},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Button text", "max_length": 50, "required": False},
                    ),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("purple-red", "Purple-Red"),
                                ("blue-green", "Blue-Green"),
                                ("light-blue", "Light Blue"),
                            ],
                            "label": "Color",
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("description", 1),
                                ("image", 2),
                                ("page", 3),
                                ("url", 4),
                                ("button_text", 5),
                                ("style", 6),
                            ]
                        ],
                        {},
                    ),
                },
                null=True,
                verbose_name="Banners",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="banners_ka",
            field=wagtail.fields.StreamField(
                [("banner", 7)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "max_length": 255, "required": False},
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Description", "required": False},
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image"},
                    ),
                    3: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Page", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "URL", "max_length": 2000, "required": False},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Button text", "max_length": 50, "required": False},
                    ),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("purple-red", "Purple-Red"),
                                ("blue-green", "Blue-Green"),
                                ("light-blue", "Light Blue"),
                            ],
                            "label": "Color",
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("description", 1),
                                ("image", 2),
                                ("page", 3),
                                ("url", 4),
                                ("button_text", 5),
                                ("style", 6),
                            ]
                        ],
                        {},
                    ),
                },
                null=True,
                verbose_name="Banners",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="banners_ru",
            field=wagtail.fields.StreamField(
                [("banner", 7)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "max_length": 255, "required": False},
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Description", "required": False},
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image"},
                    ),
                    3: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Page", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "URL", "max_length": 2000, "required": False},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Button text", "max_length": 50, "required": False},
                    ),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("purple-red", "Purple-Red"),
                                ("blue-green", "Blue-Green"),
                                ("light-blue", "Light Blue"),
                            ],
                            "label": "Color",
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("description", 1),
                                ("image", 2),
                                ("page", 3),
                                ("url", 4),
                                ("button_text", 5),
                                ("style", 6),
                            ]
                        ],
                        {},
                    ),
                },
                null=True,
                verbose_name="Banners",
            ),
        ),
    ]
