# Generated by Django 5.2.1 on 2026-09-15 14:40

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_organization_banners_organization_banners_en_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationtype",
            name="ratings_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Ratings image",
            ),
        ),
        migrations.AddField(
            model_name="organizationtype",
            name="ratings_text",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="Ratings text"),
        ),
        migrations.AddField(
            model_name="organizationtype",
            name="ratings_text_en",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="Ratings text"
            ),
        ),
        migrations.AddField(
            model_name="organizationtype",
            name="ratings_text_ka",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="Ratings text"
            ),
        ),
        migrations.AddField(
            model_name="organizationtype",
            name="ratings_text_ru",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="Ratings text"
            ),
        ),
    ]
